---
title: "Manejo recetas"
output: 
  html_document:
    code_folding: show
    highlight: espresso
    css: style.css
    keep_md: yes
    number_sections: yes
    theme: readable
    toc: yes  
    toc_float:
      collapsed: yes
      smooth_scroll: yes
      toc_depth: 3     
editor_options: 
  chunk_output_type: inline
---


```{r set-global-options, echo = FALSE}
knitr::opts_chunk$set(eval = TRUE, 
                      echo = TRUE, 
                      cache = FALSE,
                      include = TRUE,
                      collapse = FALSE,
                       dependson = NULL,
                      engine = "R", # Chunks will always have R code, unless noted
                      error = TRUE,
                      fig.path="Figures/",  # Set the figure options
                      fig.align = "center", 
                      fig.width = 12,
                      fig.height = 12)

```

```{r librerias, echo=FALSE, message=FALSE, include = FALSE, warning=FALSE}
# source("0_a_librerias.R")
# ya se cargan cuando se carguen las funciones

```

```{r}
# función para cargar un .Rmd como si se hiciese source de un .r---------------
source_rmd = function(file, ...) {
  tmp_file = tempfile(fileext = ".R")
  on.exit(unlink(tmp_file), add = TRUE)
  knitr::purl(file, output = tmp_file)
  source(file = tmp_file, ...)
}

```

```{r}
# cargar funciones de 0_funciones----------------------------------------------
source_rmd("0_b_funciones.rmd")

```

# load data

```{r cargar-datos}
# cargar datos-----------------------------------------------------------------
muestra_recetas <- readRDS(file.path("Datos", "muestra_recetas.RDS"))

```

# processing data

```{r}
# processing data--------------------------------------------------------------
prescriptions_sample <- muestra_recetas %>% 
  # max censoring date is one-year from index date
  mutate(censoring_date = pmin(index_date %m+% years(1), censoring_date)) %>% 
  # filter prescriptions inside follow-up( one-year max)
  filter(presc_start_date >= index_date,
         presc_start_date < censoring_date) %>% 
  # censoring presc_end_date to censoring date
  mutate(presc_end_date = pmin(presc_end_date, censoring_date)) %>%
  mutate(filled = if_else(filled == 0, "No", "Yes")) %>% 
  arrange(presc_start_date)

cohort_dates <- prescriptions_sample %>% 
  distinct(id, index_date, censoring_date)
  
```

# plot prescriptions

***

```{r}
# define ggplot theme----------------------------------------------------------
theme_set(theme_bw())
tema_azul <- theme_update(
  plot.background = element_rect(fill = "aliceblue", colour = "black"),
  strip.background = element_rect(colour = "black", fill = "white"))

```

```{r}
# pintar recetas del sujeto durante un año-------------------------------------
interest_id <- 6
prescriptions_id <- prescriptions_sample %>% 
  filter(id == interest_id) %>%
  arrange(presc_start_date) %>% 
  mutate(n_presc = 1:n(), .after = id) %>% 
  mutate(filled = factor(filled))

```

<br>

```{r}
# kable the table of prescriptions---------------------------------------------
kable(prescriptions_id, align = c("c"), escape = FALSE,
      table.attr = "style = \"color: black;\"",
      caption = glue("prescriptions of id {interest_id}")) %>%
  kable_styling(bootstrap_options = c("striped", 
                                      "hover", 
                                      "condensed"),
                full_width = FALSE, fixed_thead = T) %>%
  row_spec(0, bold = T, color = "white", background = "dodgerblue",
           extra_css = "vertical-align:middle") %>% 
  footnote(footnote_as_chunk = TRUE, 
           general = "one-year period prescriptions")

```

<br>

```{r plot-prescriptions, echo=FALSE, warning=FALSE, message=FALSE}
# pintar todas las recetas-----------------------------------------------------
ggplot(prescriptions_id, aes(color = prin_act_desc)) +
  geom_segment(aes(x = presc_start_date, xend = presc_end_date, 
                   y = n_presc, yend = n_presc, linetype = filled),
               size = 1,
               lineend = "round", 
               arrow = arrow(ends = "both", type = "open", 
                             length = unit(0.05, "cm"))) +
  scale_linetype_manual(name = "filled", 
                        breaks = c("No", "Yes"),
                        values = c("dotted", "solid")) +
  theme(legend.position = "bottom") +
  xlab("date") +
  ylab("prescription number") +
  scale_x_date(date_breaks = "1 month", date_labels = "%Y-%m" ) +
  scale_color_discrete(name = "Active principle") +
  ggtitle(glue("Prescriptions of individual {interest_id} in one-year period"))

```

<br>

# Extend prescription periods

***

## Prescribed periods

```{r}
# preparing the base
all_prin_acts <- prescriptions_sample %>% 
  distinct(prin_act_desc) %>% pull()

prescriptions_sample_pa1 <- prescriptions_sample %>% 
  filter(prin_act_desc == all_prin_acts[2]) %>% 
  arrange(presc_start_date)

# extend intervals
extended_base_0 <- extend_intervals(database = prescriptions_sample_pa1,
                                    i = interest_id)

# post_processing <- function(extended_base)
extended_base_id <- extended_base_0 %>% 
  transmute(
    id,
    prin_act_desc = all_prin_acts[2],
    n_period = period,
    period_start_date = zoo::as.Date(a),
    period_end_date =   zoo::as.Date(b),
    prescription = "Yes",
    filled = NA_character_) %>% 
  left_join(cohort_dates) %>% 
  # recortar periodo fin con la fecha de censura
  tidylog::mutate(period_end_date = pmin(censoring_date, period_end_date))

```

```{r}
# kable the table of prescriptions---------------------------------------------
kable(extended_base_id, align = c("c"), escape = FALSE,
      table.attr = "style = \"color: black;\"",
      caption = glue("periods of id {interest_id}")) %>%
  kable_styling(bootstrap_options = c("striped", 
                                      "hover", 
                                      "condensed"),
                full_width = FALSE, fixed_thead = T) %>%
  row_spec(0, bold = T, color = "white", background = "dodgerblue",
           extra_css = "vertical-align:middle") %>% 
  footnote(footnote_as_chunk = TRUE, 
           general = "one-year period prescriptions")

```

```{r plot-periods, echo=FALSE, warning=FALSE, message=FALSE}
# pintar todas las recetas-----------------------------------------------------
ggplot(extended_base_id, aes(color = prin_act_desc)) +
  geom_segment(aes(x = period_start_date, xend = period_end_date, 
                   y = n_period, yend = n_period),
               size = 1,
               lineend = "round", 
               arrow = arrow(ends = "both", type = "open", 
                             length = unit(0.05, "cm"))) +
  theme(legend.position = "bottom") +
  xlab("date") +
  ylab("period number") +
  scale_x_date(date_breaks = "1 month", date_labels = "%Y-%m" ) +
  scale_y_continuous(breaks =  extended_base_id %>% 
                       distinct(n_period) %>% pull()) +
  scale_color_discrete(name = "Active principle") +
  ggtitle(glue("Prescribed periods of individual {interest_id} in one-year period"))

```

## Dispensed periods

```{r}
# preparing the base
all_prin_acts <- prescriptions_sample %>% 
  distinct(prin_act_desc) %>% pull()

filled_prescriptions_sample_pa1 <- prescriptions_sample %>% 
  filter(prin_act_desc == all_prin_acts[2]) %>%
  filter(filled == "Yes") %>% 
  arrange(presc_start_date)

# extend intervals
filled_extended_base_0 <- extend_intervals(
  database = filled_prescriptions_sample_pa1,
  i = interest_id)

# post_processing <- function(extended_base)
filled_extended_base_id <- filled_extended_base_0 %>% 
  transmute(
    id,
    prin_act_desc = all_prin_acts[2],
    n_period = period,
    period_start_date = zoo::as.Date(a),
    period_end_date =   zoo::as.Date(b),
    prescription = "Yes",
    filled = "Yes") %>% 
  left_join(cohort_dates) %>% 
  # recortar periodo fin con la fecha de censura
  tidylog::mutate(period_end_date = pmin(censoring_date, period_end_date))

```

```{r}
# kable the table of prescriptions---------------------------------------------
kable(filled_extended_base_id, align = c("c"), escape = FALSE,
      table.attr = "style = \"color: black;\"",
      caption = glue("periods of id {interest_id}")) %>%
  kable_styling(bootstrap_options = c("striped", 
                                      "hover", 
                                      "condensed"),
                full_width = FALSE, fixed_thead = T) %>%
  row_spec(0, bold = T, color = "white", background = "dodgerblue",
           extra_css = "vertical-align:middle") %>% 
  footnote(footnote_as_chunk = TRUE, 
           general = "one-year period filled prescriptions")

```

```{r plot-periods, echo=FALSE, warning=FALSE, message=FALSE}
# pintar todas las recetas-----------------------------------------------------
ggplot(filled_extended_base_id, aes(color = prin_act_desc)) +
  geom_segment(aes(x = period_start_date, xend = period_end_date, 
                   y = n_period, yend = n_period),
               size = 1,
               lineend = "round", 
               arrow = arrow(ends = "both", type = "open", 
                             length = unit(0.05, "cm"))) +
  theme(legend.position = "bottom") +
  xlab("date") +
  ylab("filled period number") +
  scale_x_date(date_breaks = "1 month", date_labels = "%Y-%m" ) +
  scale_y_continuous(breaks =  filled_extended_base_id %>% 
                       distinct(n_period) %>% pull()) +
  scale_color_discrete(name = "Active principle") +
  ggtitle(glue("Filled periods of individual {interest_id} in one-year period"))

```

# Reconciliate prescription and filled periods

***

```{r}
extended_base_id
filled_extended_base_id

usethis::create_from_github(
  "https://github.com/frasansa/social_preg.git",
  destdir = file.path("C:", "Users", "fcosa", "Desktop", "GIT_Projects")
)

```

